fixed compiling issues
aleksajovanovic/p2p-server-pool pull request #5
Opened 2019-03-30 14:24 UTC by tiagovalverde

# Description
- Compiling and typos issues fixed
- Make maven project able to build
-
# Review
- [x] @aleksajovanovic

2019-03-30 21:23 UTC, aleksajovanovic requested changes

2019-03-30 21:23 UTC, aleksajovanovic commented on serverpool/src/main/java/com/ats/serverpool/network/udp/client/UDPClient.java
> +        return msg;
we should be returning a msg object with the message data set to an empty string. Passing around null objects can cause unnecessary crashes

2019-03-31 12:19 UTC, tiagovalverde reviewed
I see your point @aleksajovanovic. I made the changes, please see the my comments in the updated files.

2019-03-31 12:19 UTC, tiagovalverde commented on serverpool/src/main/java/com/ats/serverpool/Message.java
> +    public Message() {
@aleksajovanovic I added a constructor instanciating an empty Message object. Just in case I added the setter methods as well.

2019-03-31 12:19 UTC, tiagovalverde commented on serverpool/src/main/java/com/ats/serverpool/network/udp/client/UDPClient.java
> +        return new Message();
@aleksajovanovic, you are right!! I udpdated the Message object and here an empty Message object is returned instead.

2019-03-31 15:02 UTC, merged